### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by jaxnz** [Makepad-fr/fbjs#17]
Can you please give an example of how this could be used in a script?

**Comment by gakowalski** [comment]
What kind of a script?

**Comment by jaxnz** [comment]
NodeJS Script. Works in a command line, but I can't figure out how to use it in a script.

**Comment by kaanyagci** [comment]
Hi @jaxnz !

Thank you for your question! For instance `fbjs` not works as a NodeJS module. But in the next release `fbjs` will be a library and the CLI part will be imported in `socialwalker` with other social media CLI tools.

**Comment by kaanyagci** [comment]
You can find a working example in `fbjs-cli` repo.
