### ISSUE TITLE
TimeoutError and then app hangs

### ISSUE THREAD

**Issue by gakowalski** [Makepad-fr/fbjs#22]
Installed just now with
```
npm i facebook-group-posts-scraper -g --unsafe-perm
```

Version:
```
# fgps --version
2.3.0
```

> (node:35) UnhandledPromiseRejectionWarning: TimeoutError: waiting for selector "#login_form" failed: timeout 30000ms exceeded
>     at new WaitTask (/usr/local/lib/node_modules/facebook-group-posts-scraper/node_modules/puppeteer/lib/DOMWorld.js:549:28)
>     at DOMWorld._waitForSelectorOrXPath (/usr/local/lib/node_modules/facebook-group-posts-scraper/node_modules/puppeteer/lib/DOMWorld.js:478:22)
>     at DOMWorld.waitForSelector (/usr/local/lib/node_modules/facebook-group-posts-scraper/node_modules/puppeteer/lib/DOMWorld.js:432:17)
>     at Frame.waitForSelector (/usr/local/lib/node_modules/facebook-group-posts-scraper/node_modules/puppeteer/lib/FrameManager.js:627:47)
>     at Frame.<anonymous> (/usr/local/lib/node_modules/facebook-group-posts-scraper/node_modules/puppeteer/lib/helper.js:112:23)
>     at Page.waitForSelector (/usr/local/lib/node_modules/facebook-group-posts-scraper/node_modules/puppeteer/lib/Page.js:1122:29)
>     at facebookLogIn (/usr/local/lib/node_modules/facebook-group-posts-scraper/src/index.js:335:14)
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
>     at async main (/usr/local/lib/node_modules/facebook-group-posts-scraper/src/index.js:599:10)
> (node:35) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> (node:35) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by gakowalski** [comment]
Temporary fix, installing with latest code from GH instead of official NPM package:
```
npm i https://github.com/Makepad-fr/fbjs facebook-group-posts-scraper -g
```

**Comment by kaanyagci** [comment]
@gakowalski This is related to the version on `npm` is outdated. I'll fix the latest version manually and fix the CI for further releases

**Comment by kaanyagci** [comment]
Version `2.3.2` published on `npm`
