### ISSUE TITLE
Ability to login with cookies

### ISSUE THREAD

**Issue by wvffle** [Makepad-fr/fbjs#30]
I don't quite see how I'm going to pass the 2FA code every time I want to scrape the group. Also one may perceive inputting password as a security threat. Especially  if it's stored in plaintext (I have no idea if it is.)

**Comment by kaanyagci** [comment]
Hi @wvffle ,

Thank you for your feedback.  Yes, the password is stored in a plain text format on the local machine. We are using the `configstore` package for the security threat part, which is also used by many other CLI tools. 

For the cookie injection, I'm not a fan of it, but it can be a good idea to handle 2FA input. On the other hand, sadly, at this moment, I do not have enough time to implement this kind of feature. If you want, feel free to implement it and send the PR, any contributions are more than welcome :)

**Comment by kaanyagci** [comment]
Hi @wvffle ,

With the `4.0.0` version you can login with cookies. There's also a support for 2FA authentication. For further information please check the CLI repo on @Makepad-fr/fbjs-cli
