### ISSUE TITLE
Using this without authentication? 

### ISSUE THREAD

**Issue by iMrDJAi** [Makepad-fr/fbjs#33]
Should we login to see posts from public groups? No.  
I guess you should make an option to skip authentication, this is pointless in this case, unless there are limitations I'm not aware of.
Good job btw, I'm very excited for the NodeJS module support! <3

**Comment by kaanyagci** [comment]
Hello @iMrDJAi ! 

Thank you very much for your feedback. Actually, a great idea to add the skip login option for Facebook public groups. TBH I did not know there are public groups on Facebook. I will add ASAP.

Thank you for the NodeJS module support. Normally the pull request is ready, but I need to test and re-implement the CLI tool with the module before releasing it. If you want to give it a try, you can refer to #32.

Stay tuned 😎 🤓

**Comment by iMrDJAi** [comment]
@kaanyagci You're welcome, I really like this project, it can be even better than that!  
I wanna provide you some suggestions:
- For now the scrapper provides you limited data, 2 fields only aren't enough for advanced use-cases, what I'm trying to do is using the Reddit API to automatically repost form my Facebook group to my Subreddit, images and videos, post link, author profile link... are needed.
- You should probably switch to the computer version of the website to get HQ media, the mobile version seems easy to scrape but it gives you low quality.
- You need to build a class for posts data, because you can't really extract everything from a single post at once, for example Facebook doesn't provide a direct link for videos, you'll have to render the video with another implementation in a separate function.

I'll probably look up for solutions to achieve that, I'll tell you if I found something useful.

**Comment by kaanyagci** [comment]
Hi, @iMrDJAi !

The version `4.0.0` actually merged on master and published on npm. With the module approach you can skip the authentication or you can also use the CLI fbjs-cli.
