### ISSUE TITLE
Scrapping videos from Facebook

### ISSUE THREAD

**Issue by iMrDJAi** [Makepad-fr/fbjs#34]
I been searching and I found this browser API: [captureStream()](https://developers.google.com/web/updates/2016/10/capture-stream).
It allows you to capture stream from html video/audio/canvas elements:
```js
var video = document.querySelector('video')
//Capture a video stream in 30 FPS
var stream = video.captureStream(30)
```
This implementation can be used to scrape Facebook videos simply by recording the captured stream using the [MediaRecorder](https://developers.google.com/web/updates/2016/01/mediarecorder) browser api.

**Comment by kaanyagci** [comment]
Hi @iMrDJAi ,

Thank you for you feedback. I placed in P2 phase. Any contributions are more than welcome

**Comment by iMrDJAi** [comment]
> Hi @iMrDJAi ,
> 
> Thank you for you feedback. I placed in P2 phase. Any contributions are more than welcome

@kaanyagci Sounds good, I'll take a look.  
Btw the first thing that I'm planning to do before adding any new features is switching to the desktop website, I'll work on in then I'll create a pull request once I finish.
