### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by icaka5541** [Makepad-fr/fbjs#39]
fb groups:get:posts -i 689598851175466 --headfull --output=C:\Users\myname\Desktop\fc.json -c 10
Running in headless mode ? true
Спомени за родната казарма* публична група | Facebook Facebook group's posts scraped: 156 posts found
    Error: ENOENT: no such file or directory, open 'C:\Users\apollo\Desktop\fc.jsongroupname* публична група | Facebook.json'
    Code: ENOENT

**Comment by iMrDJAi** [comment]
Yeah, as I mentioned here:
https://github.com/Makepad-fr/fbjs/blob/d6024a1bfe8c524447c0cbe90521a19b09117133/src/lib/models/fb.ts#L263 https://github.com/Makepad-fr/fbjs/blob/d6024a1bfe8c524447c0cbe90521a19b09117133/src/lib/models/fb.ts#L264
Certain characters/symbols/words are not allowed in file names, not only slashes, even backslashes should be removed!  
This validation needs more work, I think the best option here is to slugify group names.
