### ISSUE TITLE
Get the post id

### ISSUE THREAD

**Issue by kaanyagci** [Makepad-fr/fbjs#52]
The post id is useful for having a sort of hash to detect the changes in a post. For instance, if a post changes by the time, we just scrape that one more time. This post id can be get from the `href` attribute of the date `a` element at the bottom of the author's name.  Once the post id is got the `GropPost` class should be updated

**Comment by iMrDJAi** [comment]
I've already done this, GG!

**Comment by iMrDJAi** [comment]
Just FYI, before I added the hovering implementation, it been giving me sometimes a hash "#" instead of the permalink in the output, hovering on that `a` element loads the href, that's how I fixed it.

**Comment by kaanyagci** [comment]
Perfect! I linked the issue with your pull request #55. Closing this as it is merged
